- name: Download deb package
  get_url: 
    url: "{{ package.url }}"
    dest: "/tmp/{{ package.file }}"

- name: Install deb dependencies
  apt:
    deb: "/tmp/{{ package.file }}"
  become: true

- name: Remove downloads
  file:
    path: "/tmp/{{ package.file }}"
    state: absent
