- name: Clone dotfiles
  git:
    dest: "{{ (ansible_user_dir | length > 0) | ternary(ansible_user_dir , '~/') }}/dotfiles"
    force: no
    recursive: yes
    repo: "{{ neovim_dotfiles['repo'] }}"
    update: yes
    version: "{{ 'version' in neovim_dotfiles | ternary(neovim_dotfiles['version'], omit) }}"
  notify: Update dotfiles owners
  ignore_errors: true # temporary fix, we should register the output and define failure accordingly https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#defining-failure

- name: Create config dir
  file:
    state: directory
    path: "{{ (ansible_user_dir | length > 0) | ternary(ansible_user_dir , '~/') }}/.config"
    owner: "{{ ansible_user_uid | default(omit) }}"
    group: "{{ ansible_user_gid | default(omit) }}"

- name: symlink neovim config
  file:
    state: link
    src: "{{ (ansible_user_dir | length > 0) | ternary(ansible_user_dir , '~/') }}/dotfiles/{{ neovim_dotfiles['path'] | default('') }}"
    dest: "{{ (ansible_user_dir | length > 0) | ternary(ansible_user_dir , '~/') }}/.config/nvim"
    owner: "{{ ansible_user_uid | default(omit) }}"
    group: "{{ ansible_user_gid | default(omit) }}"
