---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/vars'

- name: Install Neovim
  block:

  - name: Download from GitHub
    get_url:
      dest: /usr/local/bin/nvim
      force: yes
      url: "{{ neovim_url }}"
      checksum: "{{ neovim_checksum }}"
      mode: u=rx,g=rx,o=rx
    become: true

- name: Plugins dependencies
  block:

  - name: Package manager dependencies
    include_tasks: '{{ item }}'
    with_first_found:
      - files:
          - 'tasks-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
          - 'tasks-{{ ansible_distribution }}.yml'
          - 'tasks-{{ ansible_os_family }}.yml'
        ignore_errors: true
        paths:
          - '{{ role_path }}/tasks'

  - name: Python dependencies
    pip:
      state: present
      executable: "{{ neovim_pip_executable | default(omit) }}"
      name: "{{ neovim_python_dependencies }}"

  - name: NodeJS dependencies
    npm:
      name: ansible-language-server
      global: yes
      state: present
    become: true

- name: Config python support
  include_tasks: config-python.yml
  with_items:
    - python_executable: "{{ neovim_python_executable }}"
      python_support: "{{ neovim_python_support }}"
      py: python

    - python_executable: "{{ neovim_python3_executable }}"
      python_support: "{{ neovim_python3_support }}"
      py: python3
