---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/vars'

- name: Download from GitHub
  get_url:
    dest: /usr/local/bin/nvim
    force: yes
    url: "{{ nvim_url }}"
    checksum: "{{ nvim_checksum }}"
    mode: u=rx,g=rx,o=rx
  become: true

- name: Install dependencies
  include_tasks:
    file: "setup-{{ ansible_os_family }}"

- name: Neovim Python dependencies
  pip:
    state: present
    name: "{{ neovim_python_dependencies }}"
