---
- name: Define dynamic facts
  include_tasks: variables.yml

- name: Install Neovim
  include_tasks: install-neovim.yml
  when: neovim_enable_install_neovim

- name: Install Neovim Dependencies
  include_tasks: install-dependencies.yml
  when: neovim_enable_install_dependencies

- name: Neovim status
  command: /usr/local/bin/nvim --version
  register: neovim_cmd
  changed_when: false

- name: Install Neovim Dotfiles
  include_tasks: install-dotfiles.yml
  when: neovim_enable_install_dotfiles

- name: Config python support
  include_tasks: config-python.yml
  with_items:
    - python_executable: "{{ neovim_python_executable }}"
      python_support: "{{ neovim_python_support }}"
      py: python

    - python_executable: "{{ neovim_python3_executable }}"
      python_support: "{{ neovim_python3_support }}"
      py: python3

  when: neovim_enable_config
