---
- name: Neovim download yum repo
  get_url:
    url: "{{ repo }}"
    dest: "/etc/yum.repos.d/{{ repo.split('/')[-1] }}"
  become: true
  when: "repo.startswith('http') and repo.endswith('.repo')"
  with_items: "{{ neovim_repos }}"
  loop_control:
    loop_var: repo

- name: Neovim yum dependencies for plugins
  yum:
    name: "{{ neovim_dependencies }}"
    state: present
    update_cache: yes
  become: true
